name: Update Dependencies

on:
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          registry-url: https://npm.pkg.github.com/
      - run: |
          git config --global user.name "AlexMilosBene"
          git config --global user.email "alex.milos@benestudio.co"
      - run: |
          echo '@AlexMilosBene:registry=https://npm.pkg.github.com' > .npmrc
          echo 'always-auth=true' >> .npmrc
          echo '//npm.pkg.github.com/:_authToken=${{ secrets.WORKSHOP_PAT}}' >> .npmrc
      - run: npm i

